version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Update & upgrade
          no_output_timeout: 60m
          command: sudo apt-get update && sudo apt-get upgrade -y
      - run:
          name: Install pre-requisites
          no_output_timeout: 60m
          command: sudo apt-get install build-essential libncurses5-dev libssl-dev libelf-dev libgtk2.0-dev libglib2.0-dev libglade2-dev bc libncurses-dev fakeroot ccache bison flex
      - run:
          name: Copy config from existing kernel
          command: cp /boot/config-`uname -r` .config
      - run:
          name: Define config
          command: make defconfig
      - run:
          name: Clean
          command: make clean
      - run:
          name: Build
          no_output_timeout: 1200m
          command: make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-custom
      - run:
          name: Install kernel component 1
          command: sudo dpkg -i ../linux-libc-dev_5.7.14-custom-1_amd64.deb
      - run:
          name: Install kernel component 2
          command: sudo dpkg -i ../linux-image-5.7.14-custom_5.7.14-custom-1_amd64.deb
      - run:
          name: Install Python 3.x
          command: sudo apt install software-properties-common && sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update && sudo apt install python3.8
      - run:
          name: Run KUnit Tests
          command: ./tools/testing/kunit/kunit.py run 

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
