version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Update & upgrade
          no_output_timeout: 60m
          command: sudo apt-get update && sudo apt-get upgrade -y
      - run:
          name: Install pre-requisites
          no_output_timeout: 60m
          command: sudo apt-get install build-essential libncurses5-dev libssl-dev libelf-dev libgtk2.0-dev libglib2.0-dev libglade2-dev bc libncurses-dev fakeroot ccache bison flex
      - run:
          name: Copy config from existing kernel
          command: cp /boot/config-`uname -r` .config
      - run:
          name: Answer oldconfig
          command: (yes '' | make oldconfig; exit 0; 2>&1 > /dev/null)
      - run:
          name: Define config
          command: make defconfig
      - run:
          name: Clean
          command: make clean
      - run:
          name: Build
          no_output_timeout: 1200m
          command: make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-custom
      - run:
          name: Prerequisite
          command: make mrproper
      - run:
          name: Run KUnit Tests
          command: ./tools/testing/kunit/kunit.py run 

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
